---
name: test
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  json:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: node -v
      - run: npm -v
      - run: npm i -g renovate
      - run: renovate --version
      - run: renovate-config-validator --strict
  json-env:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: node -v
      - run: npm -v
      - run: npm i -g renovate
      - run: renovate --version
      - run: mv renovate.json foo.json # Rename renovate.json as renovate.json is the default target of validation
      - run: RENOVATE_CONFIG_FILE=foo.json renovate-config-validator --strict
  js:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: node -v
      - run: npm -v
      - run: npm i -g renovate
      - run: renovate --version
      - run: rm renovate.json # Remove renovate.json to exclude the target of validation
      - run: RENOVATE_CONFIG_FILE=config.js renovate-config-validator --strict
