---
name: test
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  json:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: node -v
      - run: npm -v
      - run: npm i -g renovate
      - run: renovate --version
      - run: renovate-config-validator --strict
  json-env:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: node -v
      - run: npm -v
      - run: npm i -g renovate
      - run: renovate --version
      - run: RENOVATE_CONFIG_FILE=renovate.json renovate-config-validator --strict
  js:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: node -v
      - run: npm -v
      - run: npm i -g renovate
      - run: renovate --version
      - run: rm renovate.json
      - run: RENOVATE_CONFIG_FILE=config.js renovate-config-validator --strict
